### SMC(this application)
smc.webcatalog.mongodb.host=localhost
smc.webcatalog.static.page.path=C:/Users/tfujishima/git/smc-webcatalog/src/main/resources/static/html/webcatalog/
smc.webcatalog.offline.page.path=C:/Users/tfujishima/git/smc-webcatalog/src/main/resources/static/offline/


