server.servlet.context-path=/webcatalog

spring.profiles.active=dev
#spring.resources.cache.cachecontrol.private=false
spring.web.resources.cache.cachecontrol.cache-private=false
spring.web.resources.cache.cachecontrol.cache-public=true
spring.web.resources.cache.cachecontrol.max-age=21605
spring.web.resources.cache.cachecontrol.s-max-age=21606


###random values
my.secret=${random.value}
my.number=${random.int}
my.bignumber=${random.long}
my.number.less.than.ten=${random.int(10)}
my.number.in.range=${random.int[1024,65536]}

spring.data.mongodb.repositories.enabled=false
#spring.data.mongodb.host=localhost #20240617 To comment 
#spring.data.mongodb.port=27017 #20240617 To comment

### postgresql
#spring.jpa.database=POSTGRESQL
#spring.datasource.url=jdbc:postgresql://192.168.11.121:5432/smccamp
##spring.datasource.url=jdbc:postgresql://192.168.0.33:5432/smccamp
#spring.datasource.username=smccamp
#spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

##logging.level.org.hibernate.SQL=DEBUG
##logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.SQL=INFO
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false



