### SMC(this application)
smc.webcatalog.mongodb.host=192.168.0.39
smc.webcatalog.static.page.path=/opt/tomcat/webapps/webcatalog/WEB-INF/classes/static/html/webcatalog/
smc.webcatalog.offline.page.path=/opt/tomcat/webapps/webcatalog/WEB-INF/classes/static/offline/


